version: '3.7'
services:
  biblys:
    container_name: biblys-dev-env
    image: biblys/php-dev-env:8.1
    restart: on-failure
    volumes:
      - './:/usr/src/:cached'
    ports:
      - '8088:80'
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: biblys-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: biblys
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
  db_legacy:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: biblys-mysql-legacy
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: biblys
    ports:
      - '3357:3306'
    volumes:
      - ./data/db_legacy:/var/lib/mysql
