# External Auth

api_auth:
  path: /api/auth
  controller: ApiBundle\Controller\AuthController::authAction

api_me:
  path: /api/me
  controller: ApiBundle\Controller\AuthController::meAction

# Contribution

api_contribution:
  path: /api/admin/articles/{articleId}/contributions
  methods: GET
  controller: ApiBundle\Controller\ContributionController::index

api_contribution_create:
  path: /api/admin/articles/{articleId}/contributions
  methods: POST
  controller: ApiBundle\Controller\ContributionController::create

api_contribution_update:
  path: /api/admin/articles/{articleId}/contributions/{id}
  methods: PUT
  controller: ApiBundle\Controller\ContributionController::update

api_contribution_delete:
  path: /api/admin/articles/{articleId}/contributions/{id}
  methods: DELETE
  controller: ApiBundle\Controller\ContributionController::delete

# Shipping

api_shipping:
  path: /api/admin/shipping
  methods: GET
  controller: ApiBundle\Controller\ShippingController::indexAction

api_shipping_create:
  path: /api/admin/shipping
  methods: POST
  controller: ApiBundle\Controller\ShippingController::createAction

api_shipping_update:
  path: /api/admin/shipping/{id}
  methods: PUT
  controller: ApiBundle\Controller\ShippingController::updateAction

api_shipping_delete:
  path: /api/admin/shipping/{id}
  methods: DELETE
  controller: ApiBundle\Controller\ShippingController::deleteAction

api_shipping_search:
  path: /api/shipping/search
  methods: GET
  controller: ApiBundle\Controller\ShippingController::search
